client_config_backend: settings
client_config:
  client_id: 200017578945-gsnkkatu03qiiei7vjoevnc39m8a9eso.apps.googleusercontent.com
  client_secret: 9cb5e0DO5V23LrNPjxRBIRTG

save_credentials: True
save_credentials_backend: file
save_credentials_file: resources/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive